version: '3.4'

services:
  bus:
    build:
      context: bus_service
      dockerfile: Dockerfile
    container_name: bus_service
    env_file:
      - ./bus_service/.env-dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./bus_service/src:/app/src
