version: '3.4'

services:
  bus:
    build:
      context: bus_service/src
      dockerfile: Dockerfile
    container_name: bus_service
    env_file:
      - bus_service/src/app/.env-dev
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./bus_service/src:/app/
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env-postgres
volumes:
  postgres_data: